variable "hcloud_token" {
  type = string
  sensitive = true
  description = "The hcloud token of your account ; it must be read and write"
}

variable "generated_key_name" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}

variable "domain" {
  type        = string
  description = "The tldr used to send email (ex: gmail.com)"
}
# https://stackoverflow.com/a/58841360/13369301
/*
variable "mail_subdomain" {
  type        = string
  default     = "mail.${var.domain}"
  description = "The subdomain used to send email (ex: mail.gmail.com)"
}
*/

locals {
  mail_subdomain = "mail.${var.domain}"
  private_key_path = pathexpand("${var.generated_key_name}.pem")
}
