variable "hcloud_token" {
  type = string
  sensitive = true
  description = "The hcloud token of your account ; it must be read and write"
}

variable "generated_key_name" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}